{-# LANGUAGE OverloadedStrings #-}
------------------------------------------------------------------------
-- |
-- Module      :  Graphics.Wayland.Scanner.Template
-- Copyright   :  (c) Andrea Rossato 2026
-- License     :  BSD3-style (see LICENSE)
--
-- Maintainer  :  andrea.rossato@unitn.it
-- Stability   :  stable
-- Portability :  portable
--
-- This module some templates for generating modules.
------------------------------------------------------------------------
module Graphics.Wayland.Scanner.Template where

import Data.Text (Text)
import qualified Data.Text as T

import Graphics.Wayland.Scanner.Text
import Graphics.Wayland.Scanner.Types

formatHaddockSec :: Text -> Text
formatHaddockSec t =
  unlines'
  [ "-- * " <> t
  , "--"
  , "-- $"  <> T.replace " " "_" t
  ]

formatHaddockSubSec :: Text -> Text
formatHaddockSubSec t =
  unlines'
  [ "-- ** " <> t
  , "--"
  , "-- $"   <> T.replace " " "_" t
  ]

formatArgs :: [Text] -> Text
formatArgs [] = ""
formatArgs as = T.intercalate "\n    -> " as

formatArgComment :: Text -> Text
formatArgComment "" = ""
formatArgComment c = "-- ^ " <> haddockIdent c

formatTopLevelComment :: Text -> Text
formatTopLevelComment "" = ""
formatTopLevelComment c =
  unlines'
  [ "{- |"
  , T.intercalate "\n\n" $ map (wordWrap 80) $ T.lines c
  , "-}"
  ]

formatHaddockHeader :: Name -> Text -> Text
formatHaddockHeader name desc =
  unlines'
  [ "{- |"
  , "Module      :  " <> name
  , "Copyright   :  Public Domain (generated by hs-wayland-scanner)"
  , "License     :  Public Domain (generated by hs-wayland-scanner)"
  , ""
  , "Maintainer  :  <https://codeberg.org/andrea_rossato/hs-wayland-scanner>"
  , "Stability   :  stable"
  , "Portability :  portable"
  , ""
  , T.intercalate "\n\n" $ map (wordWrap 80) $ T.lines desc
  , "-}"
  ]

moduleHeader :: HwsConfig -> SolvedProtocol -> [Text]
moduleHeader (HwsConfig _ nameSpace role _ _ _) (SolvedProtocol name desc _ deps _) =
  [ "{-# LANGUAGE ForeignFunctionInterface #-}"
  , "{-# OPTIONS_GHC -Wno-unused-imports #-}"
  , formatHaddockHeader modName desc
  , "module " <> modName <> " where"
  , ""
  , if name /= "wayland" then "import "<> T.pack nameSpace <> "." <> "Wayland.Protocol.Wayland" else ""
  , "import "<> T.pack nameSpace <> "." <> "Wayland." <> modRole <> ".Core"
  , "import "<> T.pack nameSpace <> "." <> "Wayland.Protocol." <> toHsType name
  , ""
  , "import Foreign"
  , "import Foreign.C.String"
  , "import Foreign.C.Types"
  , imports
  , "#include \"" <> name <> "-" <> T.toLower modRole <> "-protocol.h\"\n"
  ]
  where
    modName  = T.pack nameSpace  <> ".Wayland." <> modRole <> ".Protocol." <> toHsType name
    modRole  = T.pack $ show role
    modImp d = T.unlines $
               [ "import " <> T.pack nameSpace <> ".Wayland." <> modRole <> ".Protocol." <> toHsType d
               , "import " <> T.pack nameSpace <> ".Wayland.Protocol." <> toHsType d]
    imports  = T.unlines $ map modImp deps

moduleEnumHeader :: HwsConfig -> SolvedProtocol -> [Text]
moduleEnumHeader (HwsConfig _ nameSpace role _ _ _) p =
  [ "{-# LANGUAGE ForeignFunctionInterface #-}"
  , "{-# LANGUAGE PatternSynonyms #-}"
  , formatHaddockHeader modName "Data types and 'enum' shared by the client and server protocols."
  , "module " <> modName <> " where"
  , ""
  , "import Foreign"
  , if solvedProtoName p /= "wayland" then "" else "import Foreign.C.Types"
  , "#include \"" <> solvedProtoName p <> "-" <> T.toLower modRole <> "-protocol.h\"\n"
  ] ++
  if solvedProtoName p /= "wayland" then [] else
    [ "data WlRegistry"
    , "data WlDisplay"
    , "data WlInterface"
    , ""
    ] ++ wlArray
  where
    modName  = T.pack nameSpace <> ".Wayland.Protocol." <> toHsType (solvedProtoName p)
    modRole  = T.pack $ show role

-- | The core modules implement wayland-server-core and
-- wayland-client-core.
moduleCore :: HwsConfig -> [Text]
moduleCore c@(HwsConfig _ _ Client _ _ _) = moduleClientCore c
moduleCore c@(HwsConfig _ _ Server _ _ _) = moduleServerCore c

moduleClientCore :: HwsConfig -> [Text]
moduleClientCore (HwsConfig _ nameSpace role _ _ _) =
  [ formatHaddockHeader modName "An implementation of the wayland-client-core library"
  , "module " <> modName <> ".Core where\n"
  , "import Foreign"
  , "import Foreign.C.String"
  , "import Foreign.C.Types\n"
  , "import "<> T.pack nameSpace <> ".Wayland.Protocol.Wayland\n"
  , "data WlEventQueue"
  , ""
  , "-- | Connect to a Wayland display."
  , "foreign import ccall \"wl_display_connect\""
  , "  wl_display_connect :: CString -> IO (Ptr WlDisplay)"
  , ""
  , "-- | Close a connection to a Wayland display."
  , "foreign import ccall \"wl_display_disconnect\""
  , "  wl_display_disconnect :: Ptr WlDisplay -> IO ()"
  , ""
  , "-- | Get a display context's file descriptor."
  , "foreign import ccall \"wl_display_get_fd\""
  , "  wl_display_get_fd :: Ptr WlDisplay -> IO CInt"
  , ""
  , "-- | Block until all pending request are processed by the server."
  , "foreign import ccall \"wl_display_roundtrip\""
  , "  wl_display_roundtrip :: Ptr WlDisplay -> IO CInt"
  , ""
  , "-- | Block until all pending request are processed by the server."
  , "foreign import ccall \"wl_display_roundtrip_queue\""
  , "  wl_display_roundtrip_queue :: Ptr WlDisplay -> Ptr WlEventQueue -> IO CInt"
  , ""
  , "-- | Send all buffered requests on the display to the server."
  , "foreign import ccall \"wl_display_flush\""
  , "  wl_display_flush :: Ptr WlDisplay -> IO CInt"
  , ""
  , "-- | Processes incoming events. Blocks until events are read."
  , "foreign import ccall \"wl_display_dispatch\""
  , "  wl_display_dispatch :: Ptr WlDisplay -> IO CInt"
  , ""
  , "-- | Dispatch default queue events without reading from the display fd."
  , "foreign import ccall \"wl_display_dispatch_pending\""
  , "  wl_display_dispatch_pending :: Ptr WlDisplay -> IO CInt"
  , ""
  , "-- | Dispatch events in an event queue. Blocks untill there are events in the display fd."
  , "foreign import ccall \"wl_display_dispatch_queue\""
  , "  wl_display_dispatch_queue :: Ptr WlDisplay -> Ptr WlEventQueue -> IO CInt"
  , ""
  , "-- | Dispatch pending events in an event queue."
  , "foreign import ccall \"wl_display_dispatch_queue_pending\""
  , "  wl_display_dispatch_queue_pending :: Ptr WlDisplay -> Ptr WlEventQueue -> IO CInt"
  , ""
  , "-- | Create a new event queue for this display."
  , "foreign import ccall \"wl_display_create_queue\""
  , "  wl_display_create_queue :: Ptr WlDisplay -> IO (Ptr WlEventQueue)"
  , ""
  , "-- | Destroy an event queue."
  , "foreign import ccall \"wl_event_queue_destroy\""
  , "  wl_event_queue_destroy :: Ptr WlEventQueue -> IO ()"
  , ""
  , "-- | Prepare to read events from the display's file descriptor."
  , "foreign import ccall \"wl_display_prepare_read\""
  , "  wl_display_prepare_read :: Ptr WlDisplay -> IO CInt"
  , ""
  , "-- | Cancel read intention on display's fd."
  , "foreign import ccall \"wl_display_cancel_read\""
  , "  wl_display_cancel_read :: Ptr WlDisplay -> IO ()"
  , ""
  , "-- | Prepare to read events from the display's file descriptor to a queue."
  , "foreign import ccall \"wl_display_prepare_read_queue\""
  , "  wl_display_prepare_read_queue :: Ptr WlDisplay -> Ptr WlEventQueue -> IO CInt"
  , ""
  , "-- | Read events from display file descriptor."
  , "foreign import ccall \"wl_display_read_events\""
  , "  wl_display_read_events :: Ptr WlDisplay -> IO CInt"
  , ""
  , "-- | Retrieve the last error that occurred on a display."
  , "foreign import ccall \"wl_display_get_error\""
  , "  wl_display_get_error :: Ptr WlDisplay -> IO CInt"
  ]
  where
    modName = T.pack nameSpace <> ".Wayland." <> T.pack (show role)

moduleServerCore :: HwsConfig -> [Text]
moduleServerCore (HwsConfig _ nameSpace role _ _ _) =
  [ formatHaddockHeader modName "An implementation of the wayland-server-core library"
  , "module " <> modName <> ".Core where\n"
  , "import Foreign"
  , "import Foreign.C.String"
  , "import Foreign.C.Types\n"
  , "import "<> T.pack nameSpace <> ".Wayland.Protocol.Wayland\n"
  , "data WlClient"
  , "data WlResource"
  , "data WlGlobal"
  , ""
  , "foreign import ccall \"wl_display_create\""
  , "  wl_display_create :: IO (Ptr WlDisplay)"
  , ""
  , "foreign import ccall \"wl_display_destroy\""
  , "  wl_display_destroy :: Ptr WlDisplay -> IO ()"
  , ""
  , "foreign import ccall \"wl_display_run\""
  , "  wl_display_run :: Ptr WlDisplay -> IO ()"
  , ""
  , "foreign import ccall \"wl_display_add_socket_fd\""
  , "  wl_display_add_socket_fd :: Ptr WlDisplay -> CInt -> IO CInt"
  , ""
  , "foreign import ccall \"wl_display_add_socket_auto\""
  , "  wl_display_add_socket_auto :: Ptr WlDisplay -> IO CString"
  , ""
  , "type WlGlobalBindFuncCb = Ptr WlClient -> Ptr () -> Word32 -> Word32 -> IO ()"
  , ""
  , "foreign import ccall \"wl_global_create\""
  , "  wl_global_create"
  , "    :: Ptr WlDisplay"
  , "    -> Ptr WlInterface"
  , "    -> CInt"
  , "    -> Ptr ()"
  , "    -> FunPtr WlGlobalBindFuncCb"
  , "    -> IO (Ptr WlGlobal)"
  , ""
  , "foreign import ccall \"wrapper\""
  , "  mkWlGlobalBindFuncCb :: WlGlobalBindFuncCb -> IO (FunPtr WlGlobalBindFuncCb)"
  , ""
  , "foreign import ccall \"wl_resource_create\""
  , "  wl_resource_create"
  , "    :: Ptr WlClient"
  , "    -> Ptr WlInterface"
  , "    -> CInt"
  , "    -> Word32"
  , "    -> IO (Ptr WlResource)"
  , ""
  , "foreign import ccall \"wl_resource_destroy\""
  , "  wl_resource_destroy :: Ptr WlResource -> IO ()"
  , ""
  , "type WlResourceDestroyFuncCb = Ptr WlResource -> IO ()"
  , ""
  , "foreign import ccall \"wl_resource_set_implementation\""
  , "  wl_resource_set_implementation"
  , "    :: Ptr WlResource"
  , "    -> Ptr ()                         -- ^ interface struct (opaque pointer): cast with 'castPtr'"
  , "    -> Ptr ()                         -- ^ user data"
  , "    -> FunPtr WlResourceDestroyFuncCb -- ^ destroy callback"
  , "    -> IO ()"
  , ""
  , "foreign import ccall \"wrapper\""
  , "  mkWlResourceDestroyFuncCb :: WlResourceDestroyFuncCb -> IO (FunPtr WlResourceDestroyFuncCb)"
  , ""
  , "foreign import ccall \"wl_resource_post_event\""
  , "  wl_resource_post_event :: Ptr WlResource -> Word32 -> IO ()"
  ]
  where
    modName = T.pack nameSpace <> ".Wayland." <> T.pack (show role)


wlArray :: [Text]
wlArray =
  [ "#include <wayland-util.h>"
  , ""
  , "data WlArray = WlArray "
  , "    { arraySize  :: CSize"
  , "    , arrayAlloc :: CSize"
  , "    , arrayData  :: Ptr ()"
  , "    } deriving (Show, Eq)"
  , ""
  , "instance Storable WlArray where"
  , "    sizeOf _    = #size struct wl_array"
  , "    alignment _ = #alignment struct wl_array"
  , "    peek ptr = do"
  , "        s <- (#peek struct wl_array, size) ptr"
  , "        a <- (#peek struct wl_array, alloc) ptr"
  , "        d <- (#peek struct wl_array, data) ptr"
  , "        return $ WlArray s a d"
  , "    poke ptr (WlArray s a d) = do"
  , "        (#poke struct wl_array, size) ptr s"
  , "        (#poke struct wl_array, alloc) ptr a"
  , "        (#poke struct wl_array, data) ptr d"
  , ""
  , "foreign import ccall \"wl_array_init\"    wl_array_init    :: Ptr WlArray -> IO ()"
  , "foreign import ccall \"wl_array_add\"     wl_array_add     :: Ptr WlArray -> CSize -> IO (Ptr ())"
  , "foreign import ccall \"wl_array_release\" wl_array_release :: Ptr WlArray -> IO ()"
  ]

autogenComment :: Text
autogenComment =
  "/* Auto-generated by hs-wayland-scanner.\n" <>
  "Do not manually edit unless you know what you are doing. */\n\n"

autogenWrapperComment :: Text
autogenWrapperComment =
  "/* Auto-generated by hs-wayland-scanner.\n" <>
  "Aggregates Wayland protocol sources and FFI wrappers.\n" <>
  "Do not compile individual protocol .c files separately. */\n\n"
